import { Inter } from 'next/font/google'
import './globals.css'
import TopPromotion from '@/Components/TopPromotion'
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import Navbar from '@/Components/Navbar'
import ImportBsJS from '@/Components/ImportBsJS'
// import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// const DynamicBootstrap = dynamic(
//   () => require('../../node_modules/bootstrap/dist/js/bootstrap'),
//   { ssr: false }
// );
export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <ImportBsJS />
      <TopPromotion />
      <Navbar />
        {children}</body>

    </html>
  )
}
