import { Inter } from 'next/font/google'
import './globals.css'
import TopPromotion from '@/Components/TopPromotion'
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import Navbar from '@/Components/Navbar'

import ImportBsJS from '@/Components/ImportBsJS'
import Head from 'next/head'
// import { Head } from 'next/document'
// import Head from 'next/head'
// import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// const DynamicBootstrap = dynamic(
//   () => require('../../node_modules/bootstrap/dist/js/bootstrap'),
//   { ssr: false }
// );
export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
<head>
<link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
</head>

      <body className={inter.className}>
        <ImportBsJS />
      <TopPromotion />
      <Navbar />
        {children}</body>

    </html>
  )
}
